---
- name: Install packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: latest
  with_items: 
    - wireguard
    - open-iscsi
    - nfs-common

- name: Create k3s-resolv config
  ansible.builtin.copy:
    dest: "/etc/k3s-resolv.conf"
    mode: 0644
    content: |
     nameserver 1.1.1.1
     nameserver 1.0.0.1
     nameserver 2606:4700:4700::1111
     nameserver 2606:4700:4700::1001

- name: Create k3s directory
  ansible.builtin.file:
    path: "/etc/rancher/k3s"
    state: directory
    owner: "root"
    group: "root"
    mode: 0755

- name: Create k3s config
  ansible.builtin.copy:
    content: "{{ app_k3s_config }}"
    dest: "/etc/rancher/k3s/config.yaml"
    owner: "root"
    group: "root"
    force: true
    mode: 0644

- name: Create auto-deploy directory
  ansible.builtin.file:
    dest: "/var/lib/rancher/k3s/server/manifests"
    state: directory

- name: Create traefik.skip in auto-deploy
  ansible.builtin.file:
    dest: "/var/lib/rancher/k3s/server/manifests/traefik.yaml.skip"
    state: touch
    modification_time: preserve
    access_time: preserve

- name: Create local-storage.skip in auto-deploy
  ansible.builtin.file:
    dest: "/var/lib/rancher/k3s/server/manifests/local-storage.yaml.skip"
    state: touch
    modification_time: preserve
    access_time: preserve

- name: Create symlink for /etc/resolv.conf
  ansible.builtin.file:
    src: "/etc/k3s-resolv.conf"
    dest: "/etc/resolv.conf"
    state: link

- name: Copy K3s file
  ansible.builtin.copy:
    src: "k3s.service"
    dest: "/etc/systemd/system/k3s.service"
    owner: root
    group: root
    force: true
    mode: 0755
  when: inventory_hostname in groups['k3s_servers']

- name: Copy K3s node service file
  ansible.builtin.copy:
    src: "k3s-node.service"
    dest: "/etc/systemd/system/k3s.service"
    owner: root
    group: root
    force: true
    mode: 0755
  when: inventory_hostname in groups['k3s_agents']

- name: Enable and check K3s service
  ansible.builtin.systemd:
    name: k3s
    daemon_reload: yes
    state: started
    enabled: yes
