---
- name: Create k3s-resolv config
  ansible.builtin.copy:
    dest: "/etc/k3s-resolv.conf"
    mode: 0644
    content: |
     nameserver 1.1.1.1
     nameserver 1.0.0.1
     nameserver 2606:4700:4700::1111
     nameserver 2606:4700:4700::1001

- name: Create k3s directory
  ansible.builtin.file:
    path: "/etc/rancher/k3s"
    state: directory
    owner: "root"
    group: "root"
    mode: 0755

- name: Create k3s config
  ansible.builtin.copy:
    content: "{{ app_k3s_config }}"
    dest: "/etc/rancher/k3s/config.yaml"
    owner: "root"
    group: "root"
    force: true
    mode: 0644

- name: Create symlink for /etc/resolv.conf
  ansible.builtin.file:
    src: "/etc/k3s-resolv.conf"
    dest: "/etc/resolv.conf"
    state: link

- name: Copy K3s file
  ansible.builtin.copy:
    src: "k3s.service"
    dest: "/etc/systemd/system/k3s.service"
    owner: root
    group: root
    force: true
    mode: 0755
  when: inventory_hostname in groups['k3s_servers']

- name: Copy K3s node service file
  ansible.builtin.copy:
    src: "k3s-node.service"
    dest: "/etc/systemd/system/k3s.service"
    owner: root
    group: root
    force: true
    mode: 0755
  when: inventory_hostname in groups['k3s_agents']

- name: Enable and check K3s service
  systemd:
    name: k3s
    daemon_reload: yes
    state: restarted
    enabled: yes
